#!/usr/bin/env bash
# scripts/tests/fleet-revive.sh — `scripts/fleet-revive.sh` against real roots, real stores and real
# transcripts under mktemp -d. Spends no claude: `fleet revive` is intercepted by a logging shim for the
# start, and everything else (`board`, `status`, `leases`, `runtime`, `pane-guard`) is the real binary.
#
#   bash scripts/tests/fleet-revive.sh      # ~10s
#
# What is asserted, and why each case exists:
#   outside-root      no marker above the cwd → rc 2, nothing called (the partner's "error out" rule)
#   outside-home      a cwd not under $HOME → rc 2: `fleet.root.find` looks only under $HOME, so must this
#   stale-env         FLEET_HOME/FLEET_TMUX_SOCKET exported for another root are dropped, not honoured
#   claude-seed-match one DEAD Claude record whose transcript opens with a `<local-command-caveat>` meta row
#                     → its transcript is the one carrying its seed, not the decoy (same cwd, another seed),
#                     not the subagent file, not the older occupant
#   latest-of-two     two transcripts carry one seed with the SAME first timestamp (a replayed fork) → the one
#                     last written to is chosen and both are printed
#   legacy-config     a Claude record with no recorded configuration resolves the slot's owner
#   revive-all        `revive` dry-runs every record, then starts every record, then reports pane-guard
#   partial-failure   one start fails → rc 1, the other is still started, the failure is named
#   runtime-mismatch  the fleet set to codex while the records ran on claude → rc 2, no start
#   abort-recorded    an abort.json in one instant → rc 2, no start (the other record is not started either)
#   no-seed-match     a seed no transcript received → rc 2, no start
#   codex-seed-match  a DEAD Codex record whose rollout has the real shape (developer messages, a
#                     `<recommended_plugins>` user block, an AGENTS.md preamble AHEAD of the prompt) → matched
#   dry-run-refused   the verb's own refusal (executable unavailable) → rc 2, no start
#   write-time-tie    two candidates with identical write times → rc 2 (nothing says which is live)
#   search-error      a transcript path that cannot be opened → rc 2 as a failed search, never as an undelivered seed
#   duplicate-session two records resolving to one transcript → rc 2, no start
#   nothing-dead      an empty board → rc 0
set -euo pipefail
REPO="$(cd "$(dirname "$0")/../.." && pwd)"
export PYTHONPATH="$REPO/fleet/src"
python3 - "$REPO" <<'PY'
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

from fleet.pool import Pool
from fleet.store import Record, Store
from fleet.runtime_config import write_runtime

repo = Path(sys.argv[1])
script = repo / 'scripts/fleet-revive.sh'
real_fleet = repo / 'bin/fleet'
pid = os.getpid()
failures = []


def check(name, condition, detail=''):
    print(('  ok   ' if condition else '  FAIL ') + name + ('' if condition else '  ' + str(detail)[:700]))
    if not condition:
        failures.append(name)


home = Path(tempfile.mkdtemp(prefix='fleet-revive-test-'))
try:
    # The marker walk stops BELOW $HOME, so every fixture root lives one level under a fake HOME.
    env_base = dict(os.environ, HOME=str(home), FLEET_LAUNCHER_TEST_BIN=str(real_fleet))
    for key in ('FLEET_HOME', 'FLEET_ROOT', 'FLEET_TMUX_SOCKET', 'FLEET_RELEASES', 'FLEET_INSTANTS', 'CLAUDE_OWNERS_MAP'):
        env_base.pop(key, None)

    log = home / 'revive-calls.log'

    def make_shim(name, fail_id=None):
        shim = home / name
        body = ['#!/usr/bin/env bash',
                'if [ "${1:-}" = revive ]; then printf "%s\\n" "$*" >> ' + str(log) + ';']
        if fail_id:
            body.append('  case " $* " in *" --dry-run "*) exit 0 ;; *" --id ' + fail_id + ' "*) echo "FleetError: Resume not verified" >&2; exit 1 ;; esac')
        body += ['  exit 0; fi', 'exec ' + str(real_fleet) + ' "$@"', '']
        shim.write_text('\n'.join(body))
        shim.chmod(0o700)
        return shim

    shim = make_shim('fleet-shim')

    def run(cwd, mode, env=None, fleet=None, extra=None):
        e = dict(env_base if env is None else env)
        if fleet:
            e['FLEET_LAUNCHER_TEST_BIN'] = str(fleet)
        if extra:
            e.update(extra)
        return subprocess.run(['bash', str(script), mode], cwd=str(cwd), env=e, capture_output=True, text=True)

    def calls():
        return log.read_text().splitlines() if log.exists() else []

    def make_root(name, runtime=None):
        root = home / (name + '_root')
        root.mkdir()
        (root / '.fleet-root').write_text(json.dumps({'name': name}) + '\n')
        (root / 'instants').mkdir()
        if runtime:
            write_runtime(root / '.fleet', runtime)
        return root

    CAVEAT = ('<local-command-caveat>Caveat: The messages below were generated by the user while running local '
              'commands. DO NOT respond to these messages or otherwise consider them in your response unless the '
              'user explicitly asks you to.</local-command-caveat>')

    def claude_transcript(config, slot, uuid, seed_text, started, subagent=False, meta_first=False):
        project = config / 'projects' / ('-' + str(slot).strip('/').replace('/', '-'))
        path = (project / uuid / 'subagents' / 'agent-abc.jsonl') if subagent else (project / (uuid + '.jsonl'))
        path.parent.mkdir(parents=True, exist_ok=True)
        rows = [dict(type='last-prompt', sessionId=uuid), dict(type='mode', sessionId=uuid),
                dict(type='attachment', sessionId=uuid, cwd=str(slot), timestamp=started)]
        if meta_first:
            rows.append(dict(type='user', isMeta=True, sessionId=uuid, cwd=str(slot), timestamp=started,
                             message=dict(role='user', content=CAVEAT)))
        rows += [dict(type='user', sessionId=uuid, cwd=str(slot), timestamp=started,
                      message=dict(role='user', content=seed_text)),
                 dict(type='assistant', sessionId=uuid, cwd=str(slot), timestamp=started,
                      message=dict(role='assistant', content=[dict(type='text', text='ok')]))]
        path.write_text('\n'.join(json.dumps(r) for r in rows) + '\n')
        return path

    def codex_transcript(config, slot, uuid, seed_text, started):
        """The measured shape of a real rollout: developer blocks, a `<recommended_plugins>` USER block, then
        world/turn rows, an AGENTS.md USER preamble, and only then the prompt."""
        path = config / 'sessions' / '2026' / '09' / '15' / ('rollout-2026-09-15T00-00-00-' + uuid + '.jsonl')
        path.parent.mkdir(parents=True, exist_ok=True)
        def item(role, text):
            return dict(timestamp=started, type='response_item',
                        payload=dict(type='message', role=role, content=[dict(type='input_text', text=text)]))
        rows = [dict(timestamp=started, type='session_meta', payload=dict(id=uuid, cwd=str(slot), timestamp=started)),
                dict(timestamp=started, type='event_msg', payload=dict(type='task_started')),
                item('developer', '<skills_instructions>\n## Skills\nA skill is a set of local instructions'),
                item('developer', '<multi_agent_role>You are `/root`, the primary agent</multi_agent_role>'),
                item('user', '<recommended_plugins> Here is a list of plugins that are available but not installed'),
                dict(timestamp=started, type='world_state', payload={}),
                dict(timestamp=started, type='turn_context', payload={}),
                item('user', '# AGENTS.md instructions for ' + str(slot) + '\n\nRead the guidelines first.'),
                item('user', '<environment_context>\n<cwd>' + str(slot) + '</cwd>\n</environment_context>'),
                item('user', seed_text),
                item('assistant', 'ok')]
        path.write_text('\n'.join(json.dumps(r) for r in rows) + '\n')
        return path

    def dead_record(root, name, slot_name, runtime, config, when, socket, executable='/bin/true'):
        instant = root / 'instants' / ('00000000-0915' + when + '-inflight-append-' + name)
        (instant / '.fleet').mkdir(parents=True)
        seed = ('You are a dispatched worker instant on the TEST profile. Your workspace is ' + str(instant) +
                '.\n\nFIRST, orient yourself. Do not guess any of this:\n    export INSTANT=' + str(instant) +
                '\n\nThen read the charter, the handoff and the roadmap before touching anything.\n')
        (instant / '.fleet/seed.txt').write_text(seed)
        slot = root / slot_name
        slot.mkdir(exist_ok=True)
        record = Record(todo_id=name + '-0915' + when, child_instant=str(instant), base_instant='00000000',
                        slot=slot_name, tmux='dt-' + name, profile='', golden=str(slot), lineage_base='',
                        title=name, dispatched_at='2026-09-15T00:' + when[-2:] + ':00Z', runtime=runtime,
                        runtime_executable=executable, runtime_config_dir=str(config),
                        tmux_socket=socket, launched_at='2026-09-15T00:' + when[-2:] + ':05Z',
                        root=str(root))
        pool = Pool(root / '.fleet', cwd_probe=lambda path: [], alive=lambda n: False)
        pool.enroll(slot)
        pool.claim(todo_id=record.todo_id, tmux=record.tmux, base_instant='00000000',
                   child_instant=str(instant), slot=slot_name)
        Store(root / '.fleet').write(record)
        return record, instant, slot, seed

    socket = 'itrevive-%d' % pid          # no server of that name exists, so every record reads DEAD

    # ---- root A: a claude fleet (legacy default), two DEAD records ------------------------------------
    A = make_root('revivea')
    cfgA = A / '.claude'
    r1, i1, s1, seed1 = dead_record(A, 'one', 'ws1', 'claude', cfgA, '0001', socket)
    r3, i3, s3, seed3 = dead_record(A, 'three', 'ws3', 'claude', cfgA, '0003', socket)
    U1 = '11111111-1111-4111-8111-111111111111'
    DECOY = '22222222-2222-4222-8222-222222222222'
    OLD = '33333333-3333-4333-8333-333333333333'
    U3a = 'aaaaaaaa-3333-4333-8333-333333333333'
    U3b = 'bbbbbbbb-3333-4333-8333-333333333333'
    claude_transcript(cfgA, s1, U1, seed1, '2026-09-15T00:01:10Z', meta_first=True)
    claude_transcript(cfgA, s1, DECOY, 'You are a dispatched worker instant. Your workspace is /elsewhere.', '2026-09-15T00:01:20Z')
    claude_transcript(cfgA, s1, OLD, seed1.replace('0915', '0901'), '2026-09-01T00:01:10Z')
    claude_transcript(cfgA, s1, DECOY, seed1, '2026-09-15T00:01:30Z', subagent=True)   # seed text, but a subagent file
    # A fork replays the history, so both carry the SAME first timestamp; only the write time tells them apart.
    pa = claude_transcript(cfgA, s3, U3a, seed3, '2026-09-15T00:03:10Z')
    pb = claude_transcript(cfgA, s3, U3b, seed3, '2026-09-15T00:03:10Z')
    now = time.time()
    os.utime(pa, (now - 7200, now - 7200))
    os.utime(pb, (now - 60, now - 60))

    # outside-root / outside-home
    r = run(home, 'plan')
    check('outside-root: rc 2', r.returncode == 2, r.stderr)
    check('outside-root: names the marker', '.fleet-root' in r.stderr, r.stderr)
    r = run('/tmp', 'plan')
    check('outside-home: rc 2 and says the walk only looks under $HOME', r.returncode == 2 and 'not under $HOME' in r.stderr, r.stderr)

    # usage
    r = run(A, 'launcher')
    check('unknown subcommand: rc 2 with usage', r.returncode == 2 and 'usage' in r.stderr, r.stderr)

    # stale-env + claude-seed-match + latest-of-two, from a subdirectory of the root
    stale = dict(env_base, FLEET_HOME=str(home / 'nowhere/.fleet'), FLEET_TMUX_SOCKET='fleet-other',
                 FLEET_ROOT=str(home / 'nowhere'))
    r = run(A / 'ws1', 'plan', env=stale)
    check('stale-env: rc 0 from a subdirectory', r.returncode == 0, r.stderr + r.stdout)
    check('stale-env: says which exports it ignored', 'ignoring exported FLEET_HOME' in r.stderr, r.stderr)
    check('plan: names the root, its server and the binary', ('fleet root ' + str(A)) in r.stdout and 'fleet-revivea' in r.stdout
          and ('fleet binary ' + str(real_fleet)) in r.stdout, r.stdout)
    check('plan: both DEAD records', '2 DEAD record(s)' in r.stdout, r.stdout)
    check('claude-seed-match: record one → U1 past the caveat row', re.search(r'transcript\s+' + U1, r.stdout) is not None, r.stdout)
    check('claude-seed-match: the decoy, the older occupant and the subagent file are not chosen',
          DECOY not in r.stdout and OLD not in r.stdout, r.stdout)
    check('latest-of-two: record three → the one last written to, U3b', re.search(r'transcript\s+' + U3b, r.stdout) is not None, r.stdout)
    check('latest-of-two: both candidates printed with write times', ('2 transcripts carry this seed' in r.stdout) and U3a in r.stdout
          and 'last written' in r.stdout, r.stdout)
    check('plan: nothing started', 'plan only' in r.stdout and not calls(), r.stdout)

    # equal-write-time tie: nothing says which is the live thread → refusal, both printed
    os.utime(pa, (now - 60, now - 60))
    r = run(A, 'plan')
    check('write-time-tie: rc 2 naming both, nothing started', r.returncode == 2 and 'identical write times' in r.stdout
          and U3a in r.stdout and U3b in r.stdout and not calls(), r.stderr + r.stdout)
    os.utime(pa, (now - 7200, now - 7200))

    # a search error is an error, not "no transcript": a transcript path that cannot be opened (a directory
    # wearing the .jsonl name; an unreadable directory is silently skipped by the glob and is not an error)
    bogus = cfgA / 'projects' / 'bogus' / 'not-a-file.jsonl'
    bogus.mkdir(parents=True)
    try:
        r = run(A, 'plan')
    finally:
        bogus.rmdir()
    check('search-error: rc 2 reported as a failed search, not as an undelivered seed',
          r.returncode == 2 and 'transcript search failed' in r.stdout and 'never have been delivered' not in r.stdout, r.stderr + r.stdout)

    # legacy-config: no recorded configuration → the slot's owner, through claude-config-dir.sh
    owners = home / 'owners.tsv'
    owners.write_text(str(A) + '\tsomeone@example.com\n')
    legacy = Store(A / '.fleet').read(r1.todo_id)
    legacy.runtime_config_dir = ''
    Store(A / '.fleet').write(legacy)
    r = run(A, 'plan', extra={'CLAUDE_OWNERS_MAP': str(owners)})
    check('legacy-config: rc 0, owner resolved and said', r.returncode == 0 and 'the owner of the slot (legacy record)' in r.stdout
          and re.search(r'transcript\s+' + U1, r.stdout) is not None, r.stderr + r.stdout)
    Store(A / '.fleet').write(r1)

    # revive-all
    r = run(A, 'revive', fleet=shim)
    lines = calls()
    check('revive-all: rc 0', r.returncode == 0, r.stderr + r.stdout)
    dry = [l for l in lines if '--dry-run' in l]
    real = [l for l in lines if '--dry-run' not in l]
    check('revive-all: dry-run for every record before any start', len(dry) == 2 and len(real) == 2 and
          lines.index(dry[-1]) < lines.index(real[0]), lines)
    check('revive-all: exact session ids and roots on the start', any(('--id ' + r1.todo_id) in l and ('--session-id ' + U1) in l and ('--root ' + str(A)) in l for l in real)
          and any(('--id ' + r3.todo_id) in l and ('--session-id ' + U3b) in l for l in real), lines)
    check('revive-all: pane-guard reported per record', r.stdout.count('pane-guard') == 2, r.stdout)
    check('revive-all: summary', 'revived 2 of 2' in r.stdout, r.stdout)
    log.unlink()

    # partial-failure
    r = run(A, 'revive', fleet=make_shim('fleet-shim-fail', fail_id=r3.todo_id))
    real = [l for l in calls() if '--dry-run' not in l]
    check('partial-failure: rc 1, the other record still started, the failure named',
          r.returncode == 1 and len(real) == 2 and 'revived 1 of 2' in r.stderr and ('failed: ' + r3.todo_id) in r.stderr
          and 'FAILED' in r.stdout, r.stderr + r.stdout)
    log.unlink()

    # runtime-mismatch
    write_runtime(A / '.fleet', 'codex')
    r = run(A, 'revive', fleet=shim)
    check('runtime-mismatch: rc 2', r.returncode == 2, r.stderr)
    check('runtime-mismatch: says so for both records', r.stdout.count('the record ran on claude and the fleet is set to codex') == 2, r.stdout)
    check('runtime-mismatch: nothing started', not calls(), calls())
    (A / '.fleet/runtime.json').unlink()

    # abort-recorded
    (i1 / '.fleet/abort.json').write_text('{"reason": "test"}\n')
    r = run(A, 'revive', fleet=shim)
    check('abort-recorded: rc 2', r.returncode == 2, r.stderr)
    check('abort-recorded: names fleet abort', 'fleet abort --id ' + r1.todo_id in r.stdout, r.stdout)
    check('abort-recorded: the other record is not started either', not calls(), calls())
    (i1 / '.fleet/abort.json').unlink()

    # no-seed-match
    (i1 / '.fleet/seed.txt').write_text('A seed nobody received.\n')
    r = run(A, 'revive', fleet=shim)
    check('no-seed-match: rc 2, nothing started', r.returncode == 2 and not calls(), r.stderr + r.stdout)
    check('no-seed-match: names the hand path', '--session-id <uuid>' in r.stdout, r.stdout)
    (i1 / '.fleet/seed.txt').write_text(seed1)

    # ---- root B: a codex fleet, one DEAD record ------------------------------------------------------
    B = make_root('reviveb', runtime='codex')
    cfgB = B / 'codex config'
    r2, i2, s2, seed2 = dead_record(B, 'two', 'ws2', 'codex', cfgB, '0002', socket)
    U2 = '01a0a164-0c0f-7f61-8683-08d4cfd7da59'
    codex_transcript(cfgB, s2, U2, seed2, '2026-09-15T00:02:10Z')
    codex_transcript(cfgB, s2, '01a0a164-0c0f-7f61-8683-000000000000', 'another prompt', '2026-09-15T00:02:20Z')
    r = run(B, 'plan')
    check('codex-seed-match: rc 0', r.returncode == 0, r.stderr + r.stdout)
    check('codex-seed-match: record two → U2 past the injected user blocks', re.search(r'transcript\s+' + U2, r.stdout) is not None, r.stdout)
    check('codex-seed-match: runtime line', 'codex   (fleet selection: codex)' in r.stdout, r.stdout)

    # ---- root D: the verb's own refusal ---------------------------------------------------------------
    D = make_root('revived')
    cfgD = D / '.claude'
    r5, i5, s5, seed5 = dead_record(D, 'five', 'ws1', 'claude', cfgD, '0005', socket, executable=str(D / 'no-such-claude'))
    claude_transcript(cfgD, s5, U1, seed5, '2026-09-15T00:05:10Z')
    r = run(D, 'revive')                                        # the REAL verb: its dry-run refuses the executable
    check('dry-run-refused: rc 2 naming the verb refusal, nothing started',
          r.returncode == 2 and 'fleet revive --dry-run refused' in r.stdout and 'executable' in r.stdout and not calls(),
          r.stderr + r.stdout)

    # ---- root E: two records resolving to one transcript -------------------------------------------
    E = make_root('revivee')
    cfgE = E / '.claude'
    ra, ia, sa, _ = dead_record(E, 'dupa', 'ws1', 'claude', cfgE, '0006', socket)
    rb, ib, sb, _ = dead_record(E, 'dupb', 'ws2', 'claude', cfgE, '0007', socket)
    (ia / '.fleet/seed.txt').write_text('One seed text handed to two records by mistake.\n')
    (ib / '.fleet/seed.txt').write_text('One seed text handed to two records by mistake.\n')
    pea = claude_transcript(cfgE, sa, U1, 'One seed text handed to two records by mistake.', '2026-09-15T00:06:10Z')
    peb = claude_transcript(cfgE, sb, DECOY, 'One seed text handed to two records by mistake.', '2026-09-15T00:07:10Z')
    os.utime(pea, (now - 600, now - 600)); os.utime(peb, (now - 30, now - 30))     # distinct write times, so both resolve to DECOY
    (E / 'ws2').rmdir(); os.symlink(E / 'ws1', E / 'ws2')          # two leases over one directory, resolved alike
    r = run(E, 'revive', fleet=shim)
    check('duplicate-session: rc 2, names both records, nothing started',
          r.returncode == 2 and 'resolve to the same transcript' in r.stdout and r.stdout.count('resolve to the same transcript') == 1
          and not calls(), r.stderr + r.stdout)

    # ---- root C: nothing dead ------------------------------------------------------------------------
    C = make_root('revivec')
    (C / 'ws1').mkdir()
    Pool(C / '.fleet', cwd_probe=lambda path: [], alive=lambda n: False).enroll(C / 'ws1')
    r = run(C, 'revive', fleet=shim)
    check('nothing-dead: rc 0 and says so', r.returncode == 0 and 'nothing to revive' in r.stdout, r.stderr + r.stdout)
    check('nothing-dead: nothing started', not calls(), calls())
finally:
    shutil.rmtree(home, ignore_errors=True)

if failures:
    print('FAIL: ' + ', '.join(failures))
    sys.exit(1)
print('PASS: fleet-revive.sh derives root, server, slot, configuration and transcript from the directory and the records on either runtime, refuses outside a root, on a runtime mismatch, on a recorded abort, on an unmatched seed, on a verb refusal and on two records sharing a transcript without starting anything, and revives every DEAD record of the root otherwise')
PY
