#!/usr/bin/env bash
# claude-watchdog.sh — arm/disarm auto-resume for Claude CLI sessions under a root dir.
#
# Why: the Claude CLI has no built-in auto-resume; when a session hits its usage/token
# limit it halts until manual input. This wraps `claude-auto-retry` (tmux pane-scraping,
# zero token cost while waiting) so limited sessions resume automatically once the limit
# resets. A systemd --user timer re-runs a scoped reconcile every 5 min so coverage
# self-heals and newly-started sessions get picked up.
#
# Scope: this box is a single shared unix account (ubuntu, HOME=/home/ubuntu), so there
# is no per-OS-user isolation. Scoping is BEHAVIORAL, by working directory: only claude
# sessions whose cwd is under $ROOT are ever monitored. Everyone else's sessions are
# excluded and any stray monitor on them is reaped. Change the scope with
# CLAUDE_WATCHDOG_ROOT=/some/path (default: /home/ubuntu/davis_root).
#
# Only sessions running inside tmux can be covered (the tool needs a pane to scrape and
# to send-keys the resume into).
#
# Usage:
#   scripts/claude-watchdog.sh arm       Turn ON:  install+enable the timer, arm in-scope sessions now
#   scripts/claude-watchdog.sh disarm    Turn OFF: disable the timer, kill in-scope monitors
#   scripts/claude-watchdog.sh status    Show timer state + per-session coverage (default)
#
# Idempotent: arm and disarm each converge to the same end state no matter how often run.
set -u

ROOT="${CLAUDE_WATCHDOG_ROOT:-/home/ubuntu/davis_root}"
CAR="$(command -v claude-auto-retry 2>/dev/null || echo /usr/bin/claude-auto-retry)"
CAR_DIR="${HOME}/.claude-auto-retry"
EXCLUDE_FILE="${CAR_DIR}/reconcile-exclude"
UNIT_DIR="${HOME}/.config/systemd/user"
SERVICE="claude-auto-retry-davis.service"
TIMER="claude-auto-retry-davis.timer"
SELF="$(readlink -f "$0")"

: "${XDG_RUNTIME_DIR:=/run/user/$(id -u)}"
export XDG_RUNTIME_DIR

# --- helpers ---------------------------------------------------------------

# Is a path under $ROOT? Trailing slash on both sides avoids /foo matching /foobar.
in_scope() { case "${1%/}/" in "${ROOT%/}"/*) return 0 ;; *) return 1 ;; esac; }

# Live claude CLI PIDs. The native build sets its process title to "claude".
claude_pids() { pgrep -x claude 2>/dev/null; }

cwd_of() { readlink -f "/proc/$1/cwd" 2>/dev/null; }

# Extract the target claude PID from a monitor's cmdline: "... monitor.js %<pane> <pid> ...".
monitor_target_pid() { printf '%s\n' "$1" | grep -oE 'monitor\.js +%[0-9]+ +[0-9]+' | grep -oE '[0-9]+$'; }

# Rebuild the claude-auto-retry exclude list = every live claude PID whose cwd is NOT
# under $ROOT. reconcile honors this file and will refuse to arm those sessions.
rebuild_exclude() {
  mkdir -p "$CAR_DIR"
  local tmp pid cwd
  tmp="$(mktemp)"
  echo "# auto-generated by claude-watchdog.sh — out-of-scope claude PIDs (cwd not under $ROOT)" > "$tmp"
  for pid in $(claude_pids); do
    cwd="$(cwd_of "$pid")" || continue
    [ -n "$cwd" ] || continue
    in_scope "$cwd" || echo "$pid" >> "$tmp"
  done
  mv "$tmp" "$EXCLUDE_FILE"
}

# Kill armed monitors by scope. $1 = "out" (kill out-of-scope) | "in" (kill in-scope).
reap_monitors() {
  local which="$1" mpid rest tpid cwd
  pgrep -af 'monitor\.js' 2>/dev/null | while read -r mpid rest; do
    tpid="$(monitor_target_pid "$rest")"
    [ -n "${tpid:-}" ] || continue
    cwd="$(cwd_of "$tpid")"
    if [ "$which" = out ]; then
      in_scope "${cwd:-/}" || kill "$mpid" 2>/dev/null || true
    else
      in_scope "${cwd:-/}" && kill "$mpid" 2>/dev/null || true
    fi
  done
}

# (Re)write the systemd --user unit files pointing the service at THIS script.
write_units() {
  mkdir -p "$UNIT_DIR"
  cat > "${UNIT_DIR}/${SERVICE}" <<EOF
[Unit]
Description=claude-auto-retry reconcile, scoped to ${ROOT} sessions only

[Service]
Type=oneshot
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=${SELF} _reconcile
EOF
  cat > "${UNIT_DIR}/${TIMER}" <<EOF
[Unit]
Description=Run ${ROOT}-scoped claude-auto-retry reconcile every 5 min

[Timer]
OnStartupSec=30
OnUnitActiveSec=5min
Persistent=true

[Install]
WantedBy=timers.target
EOF
  systemctl --user daemon-reload
}

# --- subcommands -----------------------------------------------------------

# Internal: one scoped reconcile pass. Run by the timer; touches no timer state.
cmd_reconcile() {
  [ -x "$CAR" ] || { echo "claude-auto-retry not found at $CAR" >&2; exit 1; }
  rebuild_exclude
  reap_monitors out
  "$CAR" reconcile
}

cmd_arm() {
  [ -x "$CAR" ] || { echo "claude-auto-retry not found at $CAR (install it first)" >&2; exit 1; }
  write_units
  systemctl --user enable --now "$TIMER" >/dev/null 2>&1 || systemctl --user enable "$TIMER" 2>/dev/null || true
  systemctl --user start "$TIMER" 2>/dev/null || true
  cmd_reconcile
  echo
  cmd_status
}

cmd_disarm() {
  systemctl --user disable --now "$TIMER" 2>/dev/null || true
  reap_monitors in
  echo "Disarmed: timer stopped/disabled, in-scope monitors killed."
  echo "(sessions themselves are untouched — they just won't auto-resume on a limit hit)"
}

cmd_status() {
  local active pid cwd armed_pids any=0 st
  active="$(systemctl --user is-active "$TIMER" 2>/dev/null)"
  [ -n "$active" ] || active=inactive
  echo "Timer ($TIMER): $active     scope: $ROOT"
  armed_pids="$(pgrep -af 'monitor\.js' 2>/dev/null | while read -r _ rest; do monitor_target_pid "$rest"; done | sort -u)"
  echo "In-scope claude sessions:"
  for pid in $(claude_pids); do
    cwd="$(cwd_of "$pid")" || continue
    [ -n "$cwd" ] || continue
    in_scope "$cwd" || continue
    any=1
    if printf '%s\n' "$armed_pids" | grep -qx "$pid"; then st="ARMED"; else st="unarmed"; fi
    printf "  pid %-8s  %-48s  %s\n" "$pid" "$cwd" "$st"
  done
  [ "$any" = 0 ] && echo "  (none running under tmux)"
  return 0
}

case "${1:-status}" in
  arm)         cmd_arm ;;
  disarm)      cmd_disarm ;;
  status)      cmd_status ;;
  _reconcile)  cmd_reconcile ;;
  -h|--help|help)
    sed -n '2,40p' "$SELF" | sed 's/^# \{0,1\}//; s/^#//' ;;
  *)
    echo "Unknown command: ${1}" >&2
    echo "Usage: claude-watchdog.sh {arm|disarm|status}" >&2
    exit 2 ;;
esac
