#!/usr/bin/env bash
# claude-watchdog.sh — arm/disarm auto-resume for Claude CLI sessions under a root dir.
#
# Fully self-contained under $DAVIS (/home/ubuntu/davis_root): local Node, a local
# claude-auto-retry install, all state/config/logs, and the scheduler (a setsid daemon
# loop, NOT systemd/cron) live under $DAVIS. Nothing is written outside it.
#
# Why: the Claude CLI has no built-in auto-resume; a session that hits its usage/token
# limit halts until manual input. claude-auto-retry watches the session's tmux pane
# (zero token cost while waiting) and, once the limit resets, sends-keys a "continue".
# The daemon re-runs a scoped reconcile every $INTERVAL so new sessions get picked up
# and coverage self-heals.
#
# Scope: this box is a single shared unix account (ubuntu, HOME=/home/ubuntu), so there
# is no per-OS-user isolation. Scoping is BEHAVIORAL, by working directory: only claude
# sessions whose cwd is under $ROOT are ever monitored; everyone else's sessions are
# excluded and any stray monitor on them is reaped. Override with CLAUDE_WATCHDOG_ROOT.
#
# Only sessions running inside tmux can be covered (the tool needs a pane to scrape and
# to send-keys the resume into) — see scripts/claude-tmux.sh to launch one.
#
# Usage:
#   scripts/claude-watchdog.sh arm       Turn ON:  start the daemon + arm in-scope sessions now
#   scripts/claude-watchdog.sh disarm    Turn OFF: stop the daemon + kill in-scope monitors
#   scripts/claude-watchdog.sh status    Show daemon state + per-session coverage (default)
#
# Idempotent: arm and disarm each converge to the same end state no matter how often run.
set -u

DAVIS="/home/ubuntu/davis_root"
ROOT="${CLAUDE_WATCHDOG_ROOT:-$DAVIS}"
NODE_BIN="$DAVIS/opt/node/bin"
CAR="$DAVIS/opt/car/node_modules/.bin/claude-auto-retry"
CAR_HOME="$DAVIS"                       # HOME for the tool -> its state/config land under $DAVIS
CAR_DIR="$CAR_HOME/.claude-auto-retry"
EXCLUDE_FILE="$CAR_DIR/reconcile-exclude"
PIDFILE="$CAR_DIR/watchdog-daemon.pid"
LOGFILE="$CAR_DIR/watchdog-daemon.log"
INTERVAL="${CLAUDE_WATCHDOG_INTERVAL:-300}"
SELF="$(readlink -f "$0")"

# Run the local claude-auto-retry with local Node on PATH and HOME pinned to $DAVIS so
# all of its state/config/exclude/logs live under $DAVIS. Children (monitors) inherit this.
run_car() { PATH="$NODE_BIN:$PATH" HOME="$CAR_HOME" "$CAR" "$@"; }

# --- helpers ---------------------------------------------------------------

in_scope() { case "${1%/}/" in "${ROOT%/}"/*) return 0 ;; *) return 1 ;; esac; }
claude_pids() { pgrep -x claude 2>/dev/null; }
cwd_of() { readlink -f "/proc/$1/cwd" 2>/dev/null; }
monitor_target_pid() { printf '%s\n' "$1" | grep -oE 'monitor\.js +%[0-9]+ +[0-9]+' | grep -oE '[0-9]+$'; }

# Rebuild the exclude list = every live claude PID whose cwd is NOT under $ROOT.
rebuild_exclude() {
  mkdir -p "$CAR_DIR"
  local tmp pid cwd
  tmp="$(mktemp)"
  echo "# auto-generated by claude-watchdog.sh — out-of-scope claude PIDs (cwd not under $ROOT)" > "$tmp"
  for pid in $(claude_pids); do
    cwd="$(cwd_of "$pid")" || continue
    [ -n "$cwd" ] || continue
    in_scope "$cwd" || echo "$pid" >> "$tmp"
  done
  mv "$tmp" "$EXCLUDE_FILE"
}

# Kill armed monitors by scope. $1 = "out" (kill out-of-scope) | "in" (kill in-scope).
reap_monitors() {
  local which="$1" mpid rest tpid cwd
  pgrep -af 'monitor\.js' 2>/dev/null | while read -r mpid rest; do
    tpid="$(monitor_target_pid "$rest")"
    [ -n "${tpid:-}" ] || continue
    cwd="$(cwd_of "$tpid")"
    if [ "$which" = out ]; then
      in_scope "${cwd:-/}" || kill "$mpid" 2>/dev/null || true
    else
      in_scope "${cwd:-/}" && kill "$mpid" 2>/dev/null || true
    fi
  done
}

# --- daemon (self-contained scheduler; replaces systemd/cron) --------------

daemon_pid() { [ -f "$PIDFILE" ] && cat "$PIDFILE" 2>/dev/null; }
daemon_running() { local p; p="$(daemon_pid)"; [ -n "$p" ] && kill -0 "$p" 2>/dev/null; }

start_daemon() {
  daemon_running && return 0
  mkdir -p "$CAR_DIR"
  setsid "$SELF" _daemon >>"$LOGFILE" 2>&1 </dev/null &
  disown 2>/dev/null || true
  # Wait (briefly) for the setsid child to write its pidfile so callers see it running.
  local waited=0
  while [ "$waited" -lt 10 ]; do
    daemon_running && return 0
    sleep 0.2
    waited=$((waited + 1))
  done
}

stop_daemon() {
  local p; p="$(daemon_pid)"
  [ -n "$p" ] && kill "$p" 2>/dev/null || true
  rm -f "$PIDFILE"
}

cmd_daemon() {  # internal: the loop. Single-instance guarded.
  local existing; existing="$(daemon_pid)"
  if [ -n "$existing" ] && [ "$existing" != "$$" ] && kill -0 "$existing" 2>/dev/null; then
    exit 0
  fi
  mkdir -p "$CAR_DIR"
  echo $$ > "$PIDFILE"
  trap 'rm -f "$PIDFILE"' EXIT INT TERM
  while true; do
    cmd_reconcile >/dev/null 2>&1 || true
    sleep "$INTERVAL"
  done
}

# --- subcommands -----------------------------------------------------------

# Internal: one scoped reconcile pass (used by the daemon and by arm).
cmd_reconcile() {
  [ -x "$CAR" ] || { echo "claude-auto-retry not found at $CAR" >&2; exit 1; }
  [ -x "$NODE_BIN/node" ] || { echo "local node not found at $NODE_BIN/node" >&2; exit 1; }
  rebuild_exclude
  reap_monitors out
  run_car reconcile
}

cmd_arm() {
  cmd_reconcile
  start_daemon
  echo
  cmd_status
}

cmd_disarm() {
  stop_daemon
  reap_monitors in
  echo "Disarmed: daemon stopped, in-scope monitors killed."
  echo "(sessions themselves are untouched — they just won't auto-resume on a limit hit)"
}

cmd_status() {
  local pid cwd armed_pids any=0 st dstate
  if daemon_running; then dstate="running (pid $(daemon_pid), every ${INTERVAL}s)"; else dstate="stopped"; fi
  echo "Watchdog daemon: $dstate     scope: $ROOT"
  armed_pids="$(pgrep -af 'monitor\.js' 2>/dev/null | while read -r _ rest; do monitor_target_pid "$rest"; done | sort -u)"
  echo "In-scope claude sessions:"
  for pid in $(claude_pids); do
    cwd="$(cwd_of "$pid")" || continue
    [ -n "$cwd" ] || continue
    in_scope "$cwd" || continue
    any=1
    if printf '%s\n' "$armed_pids" | grep -qx "$pid"; then st="ARMED"; else st="unarmed"; fi
    printf "  pid %-8s  %-48s  %s\n" "$pid" "$cwd" "$st"
  done
  [ "$any" = 0 ] && echo "  (none running under tmux)"
  return 0
}

case "${1:-status}" in
  arm)        cmd_arm ;;
  disarm)     cmd_disarm ;;
  status)     cmd_status ;;
  _reconcile) cmd_reconcile ;;
  _daemon)    cmd_daemon ;;
  -h|--help|help)
    sed -n '2,44p' "$SELF" | sed 's/^# \{0,1\}//; s/^#//' ;;
  *)
    echo "Unknown command: ${1}" >&2
    echo "Usage: claude-watchdog.sh {arm|disarm|status}" >&2
    exit 2 ;;
esac
