#!/usr/bin/env bash
#
# fleet-dispatch-launcher.sh — build the `claude` shim a real `fleet dispatch` needs.
#
#     fleet-dispatch-launcher.sh <launcher-dir> <slot-path>
#     # writes <launcher-dir>/bin/claude and <launcher-dir>/seed-to-send.txt (empty), then prints
#     # the PATH prefix and config dir it resolved
#
# Then: export PATH="<launcher-dir>/bin:$PATH", run `fleet dispatch`, and write the seed into
# <launcher-dir>/seed-to-send.txt. The shim waits for it.
#
# ---------------------------------------------------------------------------------------------------
# WHY A SHIM NAMED `claude` IS UNAVOIDABLE, AND WHY THAT IS DANGEROUS
#
# `cli.py` starts a dispatched session with `sessions.start(tmux, lease.path, "claude")` — the command is
# the literal string, and nothing in `fleet` delivers a seed (a stated known gap). So the only way to hand
# a worker its briefing is to put something named `claude` earlier on PATH. That shim is then INHERITED by
# the child process and by everything the child spawns.
#
# On 2026-07-31 that produced 641 runaway claude processes in about four minutes. A plugin hook under the
# (wrong, see below) config dir invoked `claude`, which resolved to a first-generation shim that
# unconditionally re-delivered a 15KB seed and exec'd a fresh claude — which loaded the same hook, which
# invoked `claude` again. Nothing in that loop was rate-limited or idempotent.
#
# THIS SHIM IS NON-REENTRANT BY CONSTRUCTION, and that is its main job:
#
#   * It exports `FLEET_SEED_DELIVERED=1` before exec'ing. A second invocation sees the variable and
#     becomes a TRANSPARENT PASSTHROUGH — it execs the real binary with the CALLER'S OWN arguments and
#     delivers no seed. So a nested `claude --version`, or a plugin's `claude -p ...`, does exactly what
#     the caller asked and cannot spawn a seeded session.
#   * It execs the real binary by ABSOLUTE PATH, never by name, so it cannot re-enter itself even if PATH
#     resolution changes underneath it.
#
# The guard variable is deliberately exported rather than written to a file: a file would have to be
# cleaned up, and a stale one would silently disable seed delivery on the NEXT dispatch. Process
# environment is inherited exactly as far as the hazard is.
#
# ---------------------------------------------------------------------------------------------------
# WHY IT PINS CLAUDE_CONFIG_DIR
#
# The per-operator account mapping was enforced only by an interactive-zsh function, so a dispatch — which
# tmux runs non-interactively — inherited whatever `CLAUDE_CONFIG_DIR` the long-lived tmux server was
# started with. A davis coordinator ran under `chinmay_root/.claude`: another operator's credentials,
# settings and project-trust list. `claude-config-dir.sh` resolves the owner from the SLOT path, and the
# shim exports it, so the account follows the WORKSPACE rather than the accident of who opened tmux.
#
# It REFUSES rather than guessing when no root owns the slot. Running an agent under an arbitrary
# operator's account is exactly the failure this exists to stop, so a missing mapping must be loud.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
RESOLVER="$HERE/claude-config-dir.sh"

if [ "$#" -ne 2 ]; then
  echo "usage: $(basename "$0") <launcher-dir> <slot-path>" >&2
  exit 2
fi
DIR="$1"
SLOT="$2"

[ -x "$RESOLVER" ] || { echo "$(basename "$0"): missing $RESOLVER" >&2; exit 1; }
[ -d "$SLOT" ]     || { echo "$(basename "$0"): slot does not exist: $SLOT" >&2; exit 2; }

CONFIG_DIR="$("$RESOLVER" "$SLOT")" || {
  echo "$(basename "$0"): refusing to build a launcher for a slot no operator root owns: $SLOT" >&2
  echo "  add its root to the owners map first; running an agent under an arbitrary account is the" >&2
  echo "  failure this check exists to prevent." >&2
  exit 1
}

REAL_CLAUDE="${REAL_CLAUDE:-/home/ubuntu/.local/bin/claude}"
[ -x "$REAL_CLAUDE" ] || { echo "$(basename "$0"): no real claude at $REAL_CLAUDE" >&2; exit 1; }

mkdir -p "$DIR/bin"
SEED="$DIR/seed-to-send.txt"
: > "$SEED"                        # truncate, so a stale seed from an earlier dispatch cannot be picked up

cat > "$DIR/bin/claude" <<WRAP
#!/usr/bin/env bash
# GENERATED by fleet-dispatch-launcher.sh. Do not edit; regenerate.
#
# Non-reentrant seed delivery + per-operator config pinning. See the generator for why both are here.
set -uo pipefail

export CLAUDE_CONFIG_DIR="$CONFIG_DIR"

# --- passthrough: any invocation after the first is NOT a dispatch -----------------------------------
# A plugin hook, a subagent, a \`claude --version\` -- they must get the real binary with their own args.
# Without this the shim re-seeds recursively; that produced 641 processes in four minutes once.
if [ -n "\${FLEET_SEED_DELIVERED:-}" ]; then
  exec "$REAL_CLAUDE" "\$@"
fi
export FLEET_SEED_DELIVERED=1

# --- first invocation: wait for the seed, then start with it as argv --------------------------------
# The wait is load-bearing. \`fleet dispatch\` renders the seed INTO the instant and starts this session in
# the SAME call, so the caller cannot write the seed until dispatch has returned -- by which time this
# shim is already running. argv rather than send-keys, so delivery cannot lose a keystroke race.
for _ in \$(seq 1 180); do
  [ -s "$SEED" ] && break
  sleep 1
done
if [ ! -s "$SEED" ]; then
  echo "no seed arrived within 180s; starting an interactive session rather than a blank prompt" >&2
  exec "$REAL_CLAUDE" --permission-mode auto
fi
exec "$REAL_CLAUDE" --permission-mode auto "\$(cat "$SEED")"
WRAP
chmod +x "$DIR/bin/claude"

printf 'launcher\t%s/bin/claude\n' "$DIR"
printf 'seed_file\t%s\n' "$SEED"
printf 'config_dir\t%s\n' "$CONFIG_DIR"
printf 'real_claude\t%s\n' "$REAL_CLAUDE"
printf 'path_prefix\t%s/bin\n' "$DIR"
exit 0
